<?php
declare(strict_types=1);

use Magento\Framework\Escaper;
use Mulberry\Warranty\Block\Catalog\Product\View\Warranty\Container;
use Mulberry\Warranty\ViewModel\ConfigViewModel;
/**
 * @var $block Container
 * @var $escaper Escaper
 * @var $cartItemViewModel ConfigViewModel
 */

$cartItemViewModel = $block->getData('mulberryConfigViewModel');

if (!$cartItemViewModel) {
    return;
}

if (!$cartItemViewModel->canRender()) {
    return;
}
?>

<?php
/**
 * @var $block Mulberry\Warranty\Block\Catalog\Product\View\Warranty\Container
 */
?>
<?php $product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($product->isSaleable()): ?>
    <div class="product-options-mulberry">
        <div class="box-tocart">
            <div class="fieldset">
                <div class="mulberry-inline-container"></div>
                <div class="actions no-display hidden">
                    <input type="hidden" id="warranty_hash" name="warranty[hash]" value=""/>
                    <input type="hidden" id="warranty_sku" name="warranty[sku]" value="<?= $block->escapeHtml($product->getSku()); ?>"/>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        window.mulberryProductData = {
            product: {
                id: "<?= $block->escapeHtml($product->getSku()); ?>",
                title: "<?= $block->escapeHtml($block->escapeQuote($product->getName())); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $block->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $block->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $block->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $block->escapeHtml($block->getProductDescription()); ?>"
            },
            activeSelection: {
                id: "<?= $block->escapeHtml($product->getSku()); ?>",
                title: "<?= $block->escapeHtml($block->escapeQuote($product->getName())); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $block->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $block->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $block->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $block->escapeHtml($block->getProductDescription()); ?>"
            }
        };
    </script>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "mulberryProductPage": {}
            }
        }
    </script>
<?php endif; ?>
