<?php
/**
 * @category Mulberry
 * @package Mulberry\Warranty
 * @author Mulberry <support@getmulberry.com>
 * @copyright Copyright (c) 2019 Mulberry Technology Inc., Ltd (http://www.getmulberry.com)
 * @license http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>

<?php
/**
 * @var $block Mulberry\Warranty\Block\Catalog\Product\View\Warranty\Container
 */
?>
<?php $product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>

<?php if ($product->isSaleable()): ?>
    <div class="product-options-mulberry">
        <div class="box-tocart">
            <div class="fieldset">
                <div class="mulberry-inline-container"></div>
                <div class="actions">
                    <input type="hidden" id="warranty" name="warranty[<?= $block->escapeHtml($product->getSku()); ?>]" value=""/>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        window.mulberryProductData = {
            product: {
                id: "<?= $block->escapeHtml($product->getSku()); ?>",
                title: "<?= $block->escapeHtml($block->escapeQuote($product->getName())); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $block->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $block->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $block->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $block->escapeHtml($block->getProductDescription()); ?>"
            },
            activeSelection: {
                id: "<?= $block->escapeHtml($product->getSku()); ?>",
                title: "<?= $block->escapeHtml($block->escapeQuote($product->getName())); ?>",
                price: <?= (float)$product->getFinalPrice(); ?>,
                url: "<?= $block->escapeUrl($product->getProductUrl()) ?>",
                images: <?= $block->getGalleryImagesInfo(); ?>,
                meta: {
                    breadcrumbs: <?= $block->getBreadcrumbsInfo(); ?>,
                },
                description: "<?= $block->escapeHtml($block->getProductDescription()); ?>"
            }
        };

        window.mulberryConfigData = {
            "containerClass": "mulberry-inline-container",
            "magentoDomain": "<?= $block->getPlatformDomain(); ?>",
            "mulberryUrl": "<?= $block->getApiUrl(); ?>",
            "partnerUrl": "<?= $block->getPartnerUrl(); ?>",
            "retailerId": "<?= $block->getRetailerId(); ?>",
            "publicToken": "<?= $block->getPublicToken(); ?>"
        }
    </script>
    <script type="text/x-magento-init">
        {
            "#product_addtocart_form": {
                "mulberryProductPage": {}
            }
        }
    </script>
<?php endif; ?>
